/*
 Boost Software License - Version 1.0 - August 17th, 2003

 Permission is hereby granted, free of charge, to any person or organization
 obtaining a copy of the software and accompanying documentation covered by
 this license (the "Software") to use, reproduce, display, distribute,
 execute, and transmit the Software, and to prepare derivative works of the
 Software, and to permit third-parties to whom the Software is furnished to
 do so, all subject to the following:

 The copyright notices in the Software and this entire statement, including
 the above license grant, this restriction and the following disclaimer,
 must be included in all copies of the Software, in whole or in part, and
 all derivative works of the Software, unless such copies or derivative
 works are solely in the form of machine-executable object code generated by
 a source language processor.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 DEALINGS IN THE SOFTWARE.
 */

#ifndef COURSES_MANAGER_H_
#define COURSES_MANAGER_H_

#include <string>
#include <vector>
#include <memory>
using std::vector;
using std::string;
using std::shared_ptr;

#include "course.h"

namespace Faculty {

struct CoursesManager {
	void AddCourse();
	void ShowCourses();
	void AddDummyData();

	/*
	 * Return all courses, except the given ones.
	 */
	vector<shared_ptr<Course>> GetComplimentCourses(vector<shared_ptr<Course>> courses);

	/*
	 * There are circular relationships (course has students and students has course...we can't add all dummy data in same time).
	 *
	 * So we build them in a way that breaks the cycle...we also fix through that the dependent data
	 */
	void AddDummyRelationshipsData();

	vector<shared_ptr<Course>> courses_;
};

extern shared_ptr<CoursesManager> gCoursesManager;

}

#endif /* COURSES_MANAGER_H_ */
