/*
 Boost Software License - Version 1.0 - August 17th, 2003

 Permission is hereby granted, free of charge, to any person or organization
 obtaining a copy of the software and accompanying documentation covered by
 this license (the "Software") to use, reproduce, display, distribute,
 execute, and transmit the Software, and to prepare derivative works of the
 Software, and to permit third-parties to whom the Software is furnished to
 do so, all subject to the following:

 The copyright notices in the Software and this entire statement, including
 the above license grant, this restriction and the following disclaimer,
 must be included in all copies of the Software, in whole or in part, and
 all derivative works of the Software, unless such copies or derivative
 works are solely in the form of machine-executable object code generated by
 a source language processor.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 DEALINGS IN THE SOFTWARE.
 */

#include "doctor-flow-controller.h"
#include "doctors-manager.h"

#include <iostream>
#include <cassert>
using std::cout;
using std::cin;

#include "helper.h"

// TODO

namespace Faculty {

shared_ptr<DoctorsFlowController> gDoctorFlowController(new DoctorsFlowController());

bool DoctorsFlowController::IsValidUser(string user_name, string password) {
  return gDoctorsManager->GetUser(user_name, password) != nullptr;
}

void DoctorsFlowController::TakeControl(string user_name, string password) {
  current_doctor_ = gDoctorsManager->GetUser(user_name, password);

  cout << "\n\nWelcomme Doctor " << current_doctor_->name_ << ". You are logged in\n";

  cout << "\nTODO - This code block need to be implemented";

  exit(1);
}

void DoctorsFlowController::ShowMainMenu() {
  vector<string> menu = { "List Courses", "Create course", "View Course", "Log out" };

  int choice = Helper::RunMenu(menu);
}

// Run it when user selects View Course...when finish..should back to the Main menu
void DoctorsFlowController::ShowCoureOperationsMenu() {
  vector<string> menu = { "Add TAs", "List Assignments", "Create Assignment", "View Assignment", "Back" };

  int choice = Helper::RunMenu(menu);
}

void DoctorsFlowController::ShowAssignmentOperationsMenu() {
  vector<string> menu = { "Show Info", "Show Grades Report", "List Solutions", "View Solution", "Back" };

  int choice = Helper::RunMenu(menu);
}

void DoctorsFlowController::ShowAssignmentSolutionOperationsMenu() {
  vector<string> menu = { "Show Info", "Set Grade", "Set a Comment", "Back" };

  int choice = Helper::RunMenu(menu);
}

}
