/*
 Boost Software License - Version 1.0 - August 17th, 2003

 Permission is hereby granted, free of charge, to any person or organization
 obtaining a copy of the software and accompanying documentation covered by
 this license (the "Software") to use, reproduce, display, distribute,
 execute, and transmit the Software, and to prepare derivative works of the
 Software, and to permit third-parties to whom the Software is furnished to
 do so, all subject to the following:

 The copyright notices in the Software and this entire statement, including
 the above license grant, this restriction and the following disclaimer,
 must be included in all copies of the Software, in whole or in part, and
 all derivative works of the Software, unless such copies or derivative
 works are solely in the form of machine-executable object code generated by
 a source language processor.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 DEALINGS IN THE SOFTWARE.
 */

#include "student.h"
#include "assignment.h"
#include "assignment-solution.h"

namespace Faculty {

bool Student::IsMyAuthData(string user_name, string password) {
  return user_name_ == user_name && password_ == password;
}

vector<tuple<string, int, int, int>> Student::ComputeGradesStatistic() {
  vector<tuple<string, int, int, int>> returen_vec;

  // Create 3 maps, to map from course code to 3 things
  // 1) Assignments count of this course
  // 2) The sum of my grades cross all my assignments
  // 3) Sum of max grades of every assignment to know my grade / total
  map<string, int> course_code_to_total_assignments;
  map<string, int> course_code_to_my_grades_sum;
  map<string, int> course_code_to_total_grades_sum;

  for (auto solution : assignments_solutions_) {
    string code = solution->assignment_->course_->code_;

    if(solution->is_graded)
      course_code_to_my_grades_sum[code] += solution->grade_;
    course_code_to_total_grades_sum[code] += solution->assignment_->max_grade_;
    course_code_to_total_assignments[code]++;
  }

  for (auto code_grade_kv : course_code_to_my_grades_sum) {
    string code = code_grade_kv.first.c_str();

    tuple<string, int, int, int> t(code, course_code_to_total_assignments[code], course_code_to_my_grades_sum[code], course_code_to_total_grades_sum[code]);

    returen_vec.push_back(t);
  }

  return returen_vec;
}

shared_ptr<AssignmentSolution> Student::GetAssignmentSolution(shared_ptr<Assignment> assignment) {
  for (auto solution : assignments_solutions_) {
    if (assignment == solution->assignment_)  // memory address compare
      return solution;
  }
  return nullptr;
}

}
