/*
 Boost Software License - Version 1.0 - August 17th, 2003

 Permission is hereby granted, free of charge, to any person or organization
 obtaining a copy of the software and accompanying documentation covered by
 this license (the "Software") to use, reproduce, display, distribute,
 execute, and transmit the Software, and to prepare derivative works of the
 Software, and to permit third-parties to whom the Software is furnished to
 do so, all subject to the following:

 The copyright notices in the Software and this entire statement, including
 the above license grant, this restriction and the following disclaimer,
 must be included in all copies of the Software, in whole or in part, and
 all derivative works of the Software, unless such copies or derivative
 works are solely in the form of machine-executable object code generated by
 a source language processor.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 DEALINGS IN THE SOFTWARE.
 */

#ifndef STUDENT_H_
#define STUDENT_H_

#include <string>
#include <vector>
#include <memory>
#include <tuple>
#include <map>
using std::map;
using std::tuple;
using std::vector;
using std::vector;
using std::string;
using std::shared_ptr;

#include "course.h"
#include "assignment-solution.h"
#include "assignment.h"

namespace Faculty {

struct Student {
  bool IsMyAuthData(string user_name, string password);
  /*
   * Return vector about students grades. Vector length is same as registered courses count.
   *
   * Each tuple is 4 values: course code, # submitted assignments, student grades sum, total assignments grades sum
   */
  vector<tuple<string, int, int, int>> ComputeGradesStatistic();

  /*
   * Given an assignment, see if it has solution among this list or not.
   */
  shared_ptr<AssignmentSolution> GetAssignmentSolution(shared_ptr<Assignment> assignment);

  string user_name_;
  string password_;
  string name_;
  string id_;
  string email_;

  vector<shared_ptr<Course>> registered_courses_;
  vector<shared_ptr<AssignmentSolution>> assignments_solutions_;
};

}

#endif /* STUDENT_H_ */
